/**
 * (C) Copyright IBM Corporation 2021, 2026
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.openliberty.tools.maven.server;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;

import org.apache.maven.artifact.Artifact;
import org.apache.maven.artifact.versioning.ComparableVersion;
import org.apache.maven.execution.ProjectDependencyGraph;
import org.apache.maven.model.Dependency;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;
import org.apache.maven.project.ProjectBuildingException;
import org.apache.maven.project.ProjectBuildingResult;
import org.w3c.dom.Element;

import io.openliberty.tools.common.plugins.config.ServerConfigXmlDocument;
import io.openliberty.tools.common.plugins.util.BinaryScannerUtil;
import static io.openliberty.tools.common.plugins.util.BinaryScannerUtil.*;
import io.openliberty.tools.common.plugins.util.PluginExecutionException;
import io.openliberty.tools.common.plugins.util.ServerFeatureUtil;
import io.openliberty.tools.common.plugins.util.ServerFeatureUtil.FeaturesPlatforms;
import io.openliberty.tools.common.plugins.util.VersionUtility;

/**
 * This mojo generates the features required in the featureManager element in
 * server.xml. It examines the dependencies declared in the pom.xml and the
 * features already declared in the featureManager elements in the XML
 * configuration files. Then it generates any missing feature names and stores
 * them in a new featureManager element in a new XML file in the source
 * config/dropins directory.
 */
@Mojo(name = "generate-features", threadSafe = true)
public class GenerateFeaturesMojo extends PluginConfigSupport {

    public static final String HEADER = "This file was generated by the Liberty Maven Plugin and will be overwritten on subsequent runs of the liberty:generate-features goal."
            + "\n It is recommended that you do not edit this file.";
    public static final String GENERATED_FEATURES_COMMENT = "The following features were generated based on API usage detected in your application";
    public static final String NO_NEW_FEATURES_COMMENT = "No additional features generated";
    public static final String NO_CLASSES_DIR_WARNING = "Could not find classes directory to generate features against. Liberty features will not be generated. "
            + "Ensure your project has first been compiled.";
    private static final String OPEN_LIBERTY_PRODUCT_ID = "io.openliberty";
    private static final String WEBSPHERE_LIBERTY_PRODUCT_ID = "com.ibm.websphere.appserver.runtime";

    @Parameter(property = "classFiles")
    private List<String> classFiles;

    /**
     * If optimize is true, pass all class files and only user specified features to binary scanner
     * Otherwise, if optimize is false, pass only provided updated class files (if any) and all existing features to binary scanner
     */
    @Parameter(property = "optimize", defaultValue = "true")
    private boolean optimize;

    /**
     * If generateToSrc is true, then create the file containing new features in the src directory
     * Otherwise, place the file in the target directory where the Liberty server is defined.
     */
    @Parameter(property = "generateToSrc", defaultValue = "false")
    private boolean generateToSrc;

    /**
     * The isDevMode parameter is for internal use only. It is not for users.
     * This parameter must only be set to true when this mojo is called from dev mode and false otherwise.
     * This parameter is added to support generateToSrc and to cause writing the generated features file
     * to the server directory (if it exists) in stand-alone mode (not dev mode) in order to save the user
     * having to copy it manually.
     */
    @Parameter(property = "isDevMode", defaultValue = "false")
    private boolean isDevMode;

    /**
     * The useTempDirAsOutput parameter is for internal use only. It is not for users.
     * The parameter is only used when generateToSrc is false meaning we generate to serverDir.
     * It is needed in dev mode because the server is running and we need to ensure the features
     * that are generated are installed before we update a running server.
     * When the parameter is true we will write the generated features file to the special generate-features
     * temp directory.
     */
    @Parameter(property = "useTempDirAsOutput", defaultValue = "false")
    private boolean useTempDirAsOutput;

    /**
     * The useTempDirAsContext parameter is for internal use only. It is not for users.
     * It is needed in dev mode when the user updates a server config file which might affect
     * the features that will be generated. In such a case we will required the caller to copy the
     * serverDir configuration files into the special generate-features temp directory and augment it
     * with the file changed by the user. We do not do this all the time because of the performance
     * cost of copying all the files.
     * When the parameter is true we will use the generate-features temp directory as the context for
     * feature generation.
     */
    @Parameter(property = "useTempDirAsContext", defaultValue = "false")
    private boolean useTempDirAsContext;

    /**
     * Generating features is performed relative to a certain server. We only generate features
     * that are missing from a server config. By default we generate features that are missing
     * from the server directory in target/liberty/wlp/usr/servers/<server name>.
     * If generateToSrc is specified then we generate features which are missing from the Liberty
     * config specified in the src directory src/main/liberty/config.
     * We will select one server config as the context of this operation.
     */
    private File generationContextDir;

    /**
     * Liberty features are generated in the context of a certain server and they are stored in
     * an XML file in the configDir, the serverDir or a temporary directory. When using dev
     * mode we must write to the tempDir and call install-features before we can use the
     * features in the running server. When not using dev mode we can just write the features
     * to the configDir or serverDir as indicated by the generateToSrc option.
     */
    private File generationOutputDir;

    @Override
    protected void init() throws MojoExecutionException {
        super.init();
   }

    @Override
    public void execute() throws MojoExecutionException {
        init();

        if (skip) {
            getLog().info("\nSkipping generate-features goal.\n");
            return;
        }
        try {
            generateFeatures();
        } catch (PluginExecutionException e) {
            throw new MojoExecutionException("Error during generation of features.", e);
        }
    }

    /**
     * Generates features for the application given the API usage detected by the binary scanner and
     * taking any user specified features into account
     * 
     * @throws MojoExecutionException
     * @throws PluginExecutionException indicates the binary-app-scanner.jar could
     *                                  not be found
     */
    private void generateFeatures() throws MojoExecutionException, PluginExecutionException {
        // If there are downstream projects (e.g. other modules depend on this module in the Maven Reactor build order),
        // then skip generate-features on this module
        ProjectDependencyGraph graph = session.getProjectDependencyGraph();
        List<MavenProject> upstreamProjects = new ArrayList<MavenProject>();
        if (graph != null) {
        	
        	// In a multi-module build, generate-features will only be run on one project (the farthest downstream). 
        	// If this current project in the Maven Reactor is not that project or any of its upstream projects, skip it.  
        	boolean skipJars = true;
        	if("spring-boot-project".equals(getDeployPackages())) {
        		skipJars = false;
        	}
        	List<MavenProject> relevantProjects = getRelevantMultiModuleProjects(graph, skipJars);
        	if (!relevantProjects.contains(project)) {
        		getLog().info("\nSkipping module " + project.getArtifactId() + " which is not configured for the generate-features goal.\n");
        		return;
        	}

            List<MavenProject> downstreamProjects = graph.getDownstreamProjects(project, true);
            if (!downstreamProjects.isEmpty()) {
                getLog().debug("Downstream projects: " + downstreamProjects);
                return;
            } else {
                // get all upstream projects
                for (MavenProject upstreamProj : graph.getUpstreamProjects(project, true)) {
                    try {
                        // when GenerateFeaturesMojo is called from dev mode on a multi module project,
                        // the upstream project umbrella dependencies may not be up to date. Call
                        // getMavenProject to rebuild the project with the current Maven session,
                        // ensuring that the latest umbrella dependencies are loaded
                        upstreamProjects.add(getMavenProject(upstreamProj.getFile()));
                    } catch (ProjectBuildingException e) {
                        getLog().debug("Could not resolve the upstream project: " + upstreamProj.getFile()
                                + " using the current Maven session. Falling back to last resolved upstream project.");
                        upstreamProjects.add(upstreamProj); // fail gracefully, use last resolved project
                    }
                }
            }

            if (containsPreviousLibertyModule(graph)) {
                // skip this module
                return;
            }
        }
        // Ensure server dir exists to generate features to the $serverDirectory/configDropins/overrides/generated-features.xml
        if (!generateToSrc && !serverDirectory.exists()) {
            throw new MojoExecutionException("The 'generate-features' goal requires an existing Liberty server in directory " + serverDirectory.getPath() + ". Please run the 'liberty:create' goal before 'generate-features'.");
        }

        if (useTempDirAsContext) {
            // When this parameter is true it is required that the caller has copied the config into this dir.
            generationContextDir = getGeneratedFeaturesTempDir();
        } else {
            // The config dir is the one in the src directory. Otherwise generate for the target/liberty/wlp dir.
            generationContextDir = generateToSrc ? configDirectory : serverDirectory;
        }
        // When using dev mode we always generate to a temporary directory so we can call install before writing to server dir.
        generationOutputDir = useTempDirAsOutput ? getGeneratedFeaturesTempDir() : generationContextDir;

        // The executable file used to scan binaries for the Liberty features they use.
        File binaryScannerJar = getBinaryScannerJarFromRepository();
        BinaryScannerHandler binaryScannerHandler = new BinaryScannerHandler(binaryScannerJar);

        getLog().debug("--- Generate Features values ---");
        getLog().debug("Binary scanner jar: " + binaryScannerJar.getName());
        getLog().debug("optimize generate features: " + optimize);
        getLog().debug("useTempDirAsOutput (dev mode only): " + useTempDirAsOutput);
        getLog().debug("useTempDirAsContext (dev mode only): " + useTempDirAsContext);
        getLog().debug("generate to directory: " + generationOutputDir.getAbsolutePath());

        if (classFiles != null && !classFiles.isEmpty()) {
            getLog().debug("Generate features for the following class files: " + classFiles.toString());
        }

        // TODO add support for env variables
        // commented out for now as the current logic depends on the server dir existing
        // and specifying features with env variables is an edge case
        /* Map<String, File> libertyDirPropertyFiles;
        try {
            libertyDirPropertyFiles = BasicSupport.getLibertyDirectoryPropertyFiles(installDirectory, userDirectory, serverDirectory);
        } catch (IOException e) {
            getLog().debug("Exception reading the server property files", e);
            getLog().error("Error attempting to generate server feature list. Ensure your user account has read permission to the property files in the server installation directory.");
            return;
        } */

        // TODO: get user specified features that have not yet been installed in the
        // original case they appear in a server config xml document.
        // getSpecifiedFeatures may not return the features in the correct case
        // Set<String> featuresToInstall = getSpecifiedFeatures(null); 

        // get existing server features from directory of interest
        ServerFeatureUtil servUtil = getServerFeatureUtil(true, null);

        Set<String> generatedFiles = new HashSet<String>();
        generatedFiles.add(GENERATED_FEATURES_FILE_NAME);

        Set<String> existingFeatures = getServerFeatures(servUtil, generatedFiles, optimize);
        Set<String> nonCustomFeatures = new HashSet<String>(); // binary scanner only handles actual Liberty features
        for (String feature : existingFeatures) { // custom features are "usr:feature-1.0" or "myExt:feature-2.0"
            if (!feature.contains(":")) nonCustomFeatures.add(feature);
        }

        Set<String> scannedFeatureList = null;
        String eeVersion = null;
        String mpVersion = null;
        try {
            List<MavenProject> mavenProjects = new ArrayList<MavenProject>();
            mavenProjects.addAll(upstreamProjects);
            mavenProjects.add(project);
            Set<String> directories = getClassesDirectories(mavenProjects);
            if (directories.isEmpty() && (classFiles == null || classFiles.isEmpty())) {
                // log as warning and continue to call binary scanner to detect conflicts in
                // user specified features
                getLog().warn(NO_CLASSES_DIR_WARNING);
            }
            eeVersion = getEEVersion(mavenProjects, servUtil);
            mpVersion = getMPVersion(mavenProjects, servUtil);

            String logLocation = project.getBuild().getDirectory();
            String eeVersionArg = composeEEVersion(eeVersion);
            String mpVersionArg = composeMPVersion(mpVersion);
            File baseFeatureListFile = null;
            File coreFeatureListFile = null;
            String libertyGroupId = getLibertyRuntimeGroupId();
            getLog().debug("Resolve the liberty groupId used to fetch feature lists, getLibertyRuntimeGroupId()="+libertyGroupId);
            if (WEBSPHERE_LIBERTY_PRODUCT_ID.equals(libertyGroupId)) {
                baseFeatureListFile = getWebSphereFeatureListFile(FEATURE_LIST_BASE);
                coreFeatureListFile = getWebSphereFeatureListFile(FEATURE_LIST_CORE);
            } else if (OPEN_LIBERTY_PRODUCT_ID.equals(libertyGroupId)) {
                // For open liberty pass the same file to each parameter
                baseFeatureListFile = getOpenFeatureListFile();
                coreFeatureListFile = baseFeatureListFile;
            } // else should not happen, just pass null values
            scannedFeatureList = binaryScannerHandler.runBinaryScanner(nonCustomFeatures, classFiles, directories, logLocation, 
                eeVersionArg, mpVersionArg, baseFeatureListFile, coreFeatureListFile, optimize);
        } catch (BinaryScannerUtil.NoRecommendationException noRecommendation) {
            throw new MojoExecutionException(String.format(BinaryScannerUtil.BINARY_SCANNER_CONFLICT_MESSAGE3, noRecommendation.getConflicts()));
        } catch (BinaryScannerUtil.FeatureModifiedException featuresModified) {
            Set<String> userFeatures = (optimize) ? existingFeatures :
                getServerFeatures(servUtil, generatedFiles, true); // user features excludes generatedFiles
            Set<String> modifiedSet = featuresModified.getFeatures(); // a set that works after being modified by the scanner
            if (modifiedSet.containsAll(userFeatures)) {
                // none of the user features were modified, only features which were generated earlier.
                getLog().debug(
                        "FeatureModifiedException, modifiedSet containsAll userFeatures, pass modifiedSet on to generateFeatures");
                // features were modified to get a working set with the application's API usage, display warning to users and use modified set
                getLog().warn(featuresModified.getMessage());
                scannedFeatureList = modifiedSet;
            } else {
                Set<String> allAppFeatures = featuresModified.getSuggestions(); // suggestions are scanned from binaries
                allAppFeatures.addAll(userFeatures); // scanned plus configured features were detected to be in conflict
                getLog().debug("FeatureModifiedException, combine suggestions from scanner with user features in error msg");
                throw new MojoExecutionException(
                        String.format(BinaryScannerUtil.BINARY_SCANNER_CONFLICT_MESSAGE1, allAppFeatures, modifiedSet));

            }
        } catch (BinaryScannerUtil.RecommendationSetException showRecommendation) {
            if (showRecommendation.isExistingFeaturesConflict()) {
                throw new MojoExecutionException(String.format(BinaryScannerUtil.BINARY_SCANNER_CONFLICT_MESSAGE2, showRecommendation.getConflicts(), showRecommendation.getSuggestions()));
            } else {
                throw new MojoExecutionException(String.format(BinaryScannerUtil.BINARY_SCANNER_CONFLICT_MESSAGE1, showRecommendation.getConflicts(), showRecommendation.getSuggestions()));
            }
        } catch (BinaryScannerUtil.FeatureUnavailableException featureUnavailable) {
            throw new MojoExecutionException(String.format(BinaryScannerUtil.BINARY_SCANNER_CONFLICT_MESSAGE5, featureUnavailable.getConflicts(), featureUnavailable.getMPLevel(), featureUnavailable.getEELevel(), featureUnavailable.getUnavailableFeatures()));
        } catch (BinaryScannerUtil.IllegalTargetComboException illegalCombo) {
            throw new MojoExecutionException(String.format(BinaryScannerUtil.BINARY_SCANNER_INVALID_COMBO_MESSAGE, eeVersion, mpVersion));
        } catch (BinaryScannerUtil.IllegalTargetException illegalTargets) {
            String messages = buildInvalidArgExceptionMessage(illegalTargets.getEELevel(), illegalTargets.getMPLevel(), eeVersion, mpVersion);
            throw new MojoExecutionException(messages);
        } catch (PluginExecutionException x) {
            // throw an error when there is a problem not caught in runBinaryScanner()
            Object o = x.getCause();
            if (o != null) {
                getLog().debug("Caused by exception:" + x.getCause().getClass().getName());
                getLog().debug("Caused by exception message:" + x.getCause().getMessage());
            }
            throw new MojoExecutionException("Failed to generate a working set of features. " + x.getMessage(), x);
        }

        Set<String> missingLibertyFeatures = new HashSet<String>();
        if (scannedFeatureList != null) {
            missingLibertyFeatures.addAll(scannedFeatureList);

            servUtil.setLowerCaseFeatures(false);
            // get set of user defined features so they can be omitted from the generated
            // file that will be written
            FeaturesPlatforms fp = servUtil.getServerFeatures(generationContextDir, serverXmlFile, new HashMap<String, File>(),
                    generatedFiles);
            Set<String> userDefinedFeatures = optimize ? existingFeatures : (fp !=null) ? fp.getFeatures(): new HashSet<String>();
            getLog().debug("User defined features:" + userDefinedFeatures);
            servUtil.setLowerCaseFeatures(true);
            if (userDefinedFeatures != null) {
                missingLibertyFeatures.removeAll(userDefinedFeatures);
            }
        }
        getLog().debug("Features detected by binary scanner which are not in server.xml" + missingLibertyFeatures);

        // generate the new features into an xml file in the correct context directory
        // The ServerConfigXmlDocument class will create the directories if needed.
        File generatedXmlFile = new File(generationOutputDir, GENERATED_FEATURES_FILE_PATH);

        // For standalone goal (not dev mode) with generateToSrc=true, also write to server dir if it exists
        boolean shouldWriteToServerDir = !isDevMode && generateToSrc && (serverDirectory != null) && serverDirectory.exists();
        File serverDirXmlFile = null;
        if (shouldWriteToServerDir) {
            serverDirXmlFile = new File(serverDirectory, GENERATED_FEATURES_FILE_PATH);
        }

        try {
            if (missingLibertyFeatures.size() > 0) {
                Set<String> existingGeneratedFeatures = getGeneratedFeatures(servUtil, generatedXmlFile);
                if (!missingLibertyFeatures.equals(existingGeneratedFeatures)) {
                    // Create special XML file to contain generated features.
                    ServerConfigXmlDocument configDocument = ServerConfigXmlDocument.newInstance();
                    configDocument.createComment(HEADER);
                    Element featureManagerElem = configDocument.createFeatureManager();
                    configDocument.createComment(featureManagerElem, GENERATED_FEATURES_COMMENT);
                    for (String missing : missingLibertyFeatures) {
                        getLog().debug(String.format("Adding missing feature %s to %s.", missing, GENERATED_FEATURES_FILE_PATH));
                        configDocument.createFeature(missing);
                    }
                    // Output log messages before writing file as the file change event kicks off other dev mode actions
                    getLog().info("Generated the following features: " + missingLibertyFeatures);
                    printCommonMessages(eeVersion, mpVersion, generatedXmlFile);
                    configDocument.writeXMLDocument(generatedXmlFile);
                    getLog().debug("Created file " + generatedXmlFile.getAbsolutePath());

                    // For standalone mode with generateToSrc=true, also write to server directory
                    if (shouldWriteToServerDir) {
                        if (writeToServerDir(configDocument, serverDirXmlFile)) {
                            getLog().debug("Also created file " + serverDirXmlFile.getAbsolutePath());
                        }
                    }
                } else {
                    getLog().info("No change to the generated feature list: " + missingLibertyFeatures);
                    printCommonMessages(eeVersion, mpVersion, generatedXmlFile);
                }
            } else {
                getLog().info("No additional features were generated.");
                if (generatedXmlFile.exists()) {
                    // generated-features.xml exists but no additional features were generated
                    // create empty features list with comment
                    ServerConfigXmlDocument configDocument = ServerConfigXmlDocument.newInstance();
                    configDocument.createComment(HEADER);
                    Element featureManagerElem = configDocument.createFeatureManager();
                    configDocument.createComment(featureManagerElem, NO_NEW_FEATURES_COMMENT);
                    configDocument.writeXMLDocument(generatedXmlFile);

                    // For standalone mode with generateToSrc=true, also write to server directory
                    if (shouldWriteToServerDir && serverDirXmlFile.exists()) {
                        writeToServerDir(configDocument, serverDirXmlFile);
                    }
                }
            }
        } catch (ParserConfigurationException | TransformerException | IOException e) {
            getLog().debug("Exception creating the server features file", e);
            throw new MojoExecutionException(
                    "Automatic generation of features failed. Error attempting to create the "
                            + generatedXmlFile.getAbsolutePath()
                            + ". Ensure your ID has write permission to the directory the generated features file will be written to.",
                    e);
        }

    }

    /*
     * This method prints the output for both cases when features are generated (i.e., new features were generated or the same set)
     */
    private void printCommonMessages(String eeVersion, String mpVersion, File generatedXmlFile) {
        getLog().info("The generated feature list has been written to the following file: " + generatedXmlFile.getAbsolutePath());
        if (eeVersion == null && mpVersion == null) {
            getLog().info("Verify the generated feature list meets the needs of your application." +
            " If you see features missing or features at unexpected versions, please add the expected features to your server configuration" +
            (isDevMode ? "." : " and run the generate-features goal again."));
        }
    }

    /*
     * This routine writes an xml document to the specififed file and returns false if there is an exception 
     * while writing or true otherwise.
     */
    private boolean writeToServerDir(ServerConfigXmlDocument configDocument, File serverDirXmlFile) {
        try {
            configDocument.writeXMLDocument(serverDirXmlFile);
        } catch (TransformerException | IOException e) {
            getLog().warn("Failed to write generated-features.xml to server directory: "
                + serverDirXmlFile.getAbsolutePath() + ". Ensure your ID has write permission to the server configuration directory. "
                + e.getMessage());
            return false;
        }
        return true;
    }

    private Set<String> getServerFeatures(ServerFeatureUtil servUtil, Set<String> generatedFiles, boolean excludeGenerated) {
        return getServerFeaturesPlatforms(servUtil, generatedFiles, excludeGenerated, true);
    }
    private Set<String> getServerPlatforms(ServerFeatureUtil servUtil, Set<String> generatedFiles, boolean excludeGenerated) {
        return getServerFeaturesPlatforms(servUtil, generatedFiles, excludeGenerated, false); // platforms
    }

    // Get the features from the server config and optionally exclude the specified config files from the search.
    private Set<String> getServerFeaturesPlatforms(ServerFeatureUtil servUtil, Set<String> generatedFiles, boolean excludeGenerated, boolean features) {
        servUtil.setLowerCaseFeatures(false);
        // if optimizing, ignore generated files when passing in existing features to
        // binary scanner
        FeaturesPlatforms fp = servUtil.getServerFeatures(generationContextDir, serverXmlFile,
                new HashMap<String, File>(), excludeGenerated ? generatedFiles : null); // pass generatedFiles to exclude them
        servUtil.setLowerCaseFeatures(true);
        if (fp == null) {
            return new HashSet<String>();
        } else if (features) {
            return fp.getFeatures();
        } // else
        return fp.getPlatforms();
    }

    // returns the features specified in the generated-features.xml file in the generation context directory
    private Set<String> getGeneratedFeatures(ServerFeatureUtil servUtil, File generatedFeaturesFile) {
        servUtil.setLowerCaseFeatures(false);
        FeaturesPlatforms result = servUtil.getServerXmlFeatures(new FeaturesPlatforms(), generationContextDir,
                generatedFeaturesFile, null, null);
        servUtil.setLowerCaseFeatures(true);
        Set<String> features = new HashSet<String>();
        if (result != null) {
        	features = result.getFeatures();
        }
        return features;
    }

    // returns the hidden directory we use for generate-features special purposes
    private File getGeneratedFeaturesTempDir() {
        return new File(project.getBuild().getDirectory(), GENERATED_FEATURES_TEMP_DIR);
    }

    /**
     * Gets the binary scanner jar file from the local cache.
     * Downloads it first from connected repositories such as Maven Central if a newer release is available than the cached version.
     * Note: Maven updates artifacts daily by default based on the last updated timestamp. Users should use 'mvn -U' to force updates if needed.
     * 
     * @return The File object of the binary scanner jar in the local cache.
     * @throws PluginExecutionException
     */
    private File getBinaryScannerJarFromRepository() throws PluginExecutionException {
        try {
            return getArtifact(BINARY_SCANNER_MAVEN_GROUP_ID, BINARY_SCANNER_MAVEN_ARTIFACT_ID, BINARY_SCANNER_MAVEN_TYPE, BINARY_SCANNER_MAVEN_VERSION).getFile();
        } catch (Exception e) {
            throw new PluginExecutionException("Could not retrieve the artifact " + BINARY_SCANNER_MAVEN_GROUP_ID + "."
                    + BINARY_SCANNER_MAVEN_ARTIFACT_ID
                    + " needed for liberty:generate-features. Ensure you have a connection to Maven Central or another repository that contains the "
                    + BINARY_SCANNER_MAVEN_GROUP_ID + "." + BINARY_SCANNER_MAVEN_ARTIFACT_ID
                    + ".jar configured in your pom.xml.",
                    e);
        }
    }

    /*
     * Gets the file containing the Open Liberty feature list from the local cache.
     * Downloads it first from connected repositories such as Maven Central if a newer release is available than the cached version.
     * Note: Maven updates artifacts daily by default based on the last updated timestamp. Users should use 'mvn -U' to force
     * updates if needed.
     * 
     * @return The File object of the feature list in the local cache or null if version number not available
     */
    private static String OPEN_LIBERTY_FEATURE_LIST_START = "25.0.0.7";
    private File getOpenFeatureListFile() throws MojoExecutionException {
        String libertyVersion = getLibertyRuntimeVersion();
        if (libertyVersion == null) {
            return null;
        }
        // Feature lists were first published for 25.0.0.7. For liberty releases prior to this simply use the
        // earliest available feature list, 25.0.0.7.
        if (VersionUtility.compareArtifactVersion(libertyVersion, OPEN_LIBERTY_FEATURE_LIST_START, true) < 0) {
            libertyVersion = OPEN_LIBERTY_FEATURE_LIST_START;
        }
        libertyVersion = "[" + libertyVersion + "]"; // Maven syntax to specify an exact version, not a range
        return getArtifact(OL_FEATURELIST_GROUP_ID, OL_FEATURELIST_ARTIFACT_ID, OL_FEATURELIST_TYPE, libertyVersion).getFile();
    }

    /*
     * Gets the file containing the indicated Websphere feature list from the local cache.
     * Downloads it first from connected repositories such as Maven Central if a newer release is available than the cached version.
     * Note: Maven updates artifacts daily by default based on the last updated timestamp. Users should use 'mvn -U' to force
     * updates if needed.
     * 
     * @return The File object of the feature list in the local cache.
     */
    private static String WEBSPHERE_LIBERTY_FEATURE_LIST_START = "25.0.0.7";
    private static String WEBSPHERE_LIBERTY_FEATURE_LIST_CONTINUE = "25.0.0.10";
    private static String WEBSPHERE_LIBERTY_FEATURE_LIST_END = "25.0.0.12";
    private static String FEATURE_LIST_BASE = "base";
    private static String FEATURE_LIST_CORE = "core";
    private File getWebSphereFeatureListFile(String featureListVar) throws MojoExecutionException {
        // Feature lists are only available for 25.0.0.7 and 25.0.0.10-25.0.0.12.
        // For releases earlier than 25.0.0.10 use 25.0.0.7, for releases after 25.0.0.12 use 25.0.0.12.
        String libertyGroupId, libertyArtifactId;
        String libertyVersion = getLibertyRuntimeVersion();
        if (libertyVersion == null) {
            return null;
        }
        // There is a value for 25.0.0.7 but not for 25.0.0.8 or 25.0.0.9 and none for <25.0.0.7
        // so for any liberty <25.0.0.10 use the 07 values
        if (VersionUtility.compareArtifactVersion(libertyVersion, WEBSPHERE_LIBERTY_FEATURE_LIST_CONTINUE, true) < 0) {
            libertyGroupId = WS1_FEATURELIST_GROUP_ID;
            libertyVersion = WEBSPHERE_LIBERTY_FEATURE_LIST_START;
        } else { // 25.0.0.10 and up
            libertyGroupId = WS2_FEATURELIST_GROUP_ID;
            // if >25.0.0.12 just use 25.0.0.12
            if (VersionUtility.compareArtifactVersion(libertyVersion, WEBSPHERE_LIBERTY_FEATURE_LIST_END, true) > 0) {
                libertyVersion = WEBSPHERE_LIBERTY_FEATURE_LIST_END;
            } // else liberty version is 25.0.0.10-25.0.0.12
        }
        if (featureListVar.equals(FEATURE_LIST_BASE)) {
            libertyArtifactId = WSBASE_FEATURELIST_ARTIFACT_ID;
        } else {
            libertyArtifactId = WSCORE_FEATURELIST_ARTIFACT_ID;
        }
        libertyVersion = "[" + libertyVersion + "]"; // Maven syntax to specify an exact version, not a range
        getLog().debug("WebSphere Liberty feature list coordinates, libertyGroupId="+libertyGroupId+" libertyArtifactId="+libertyArtifactId+" WS_FEATURELIST_TYPE="+WS_FEATURELIST_TYPE+" libertyVersion="+libertyVersion);
        return getArtifact(libertyGroupId, libertyArtifactId, WS_FEATURELIST_TYPE, libertyVersion).getFile();
    }

    // resolve the Liberty version from one of the sources
    private String getLibertyRuntimeVersion() throws MojoExecutionException {
        // Check if libertyRuntimeVersion property is set (highest priority)
        if (libertyRuntimeVersion != null && !libertyRuntimeVersion.isEmpty()) {
            return libertyRuntimeVersion;
        } else if (assemblyArtifact != null) {
            // Resolve the artifact to get its version
            Artifact artifact = getResolvedArtifact(assemblyArtifact);
            if (artifact != null) {
                return artifact.getVersion();
            }
        }
        return null;
    }

    // resolve the Liberty GroupId from one of the sources
    private String getLibertyRuntimeGroupId() throws MojoExecutionException {
        // Check if libertyRuntimeGroupId property is set (highest priority)
        if (libertyRuntimeGroupId != null && !libertyRuntimeGroupId.isEmpty()) {
            return libertyRuntimeGroupId;
        } else if (assemblyArtifact != null) {
            // Resolve the artifact to get its values
            Artifact artifact = getResolvedArtifact(assemblyArtifact);
            if (artifact != null) {
                return artifact.getGroupId();
            }
        }
        return null;
    }

    // Return a list containing the classes directory of the Maven projects (upstream projects and main project)
    private Set<String> getClassesDirectories(List<MavenProject> mavenProjects) throws MojoExecutionException {
        Set<String> dirs = new HashSet<String>();
        String classesDirName = null;
        getLog().debug("For binary scanner gathering Java build output directories for Maven projects, size="
                + mavenProjects.size());
        for (MavenProject mavenProject : mavenProjects) {
            classesDirName = getClassesDirectory(mavenProject.getBuild().getOutputDirectory());
            if (classesDirName != null) {
                dirs.add(classesDirName);
            }
        }
        for (String s : dirs) {
            getLog().debug("Found dir:" + s);
        }
        return dirs;
    }

    // Check one directory and if it exists return its canonical path (or absolute path if error).
    private String getClassesDirectory(String outputDir) {
        File classesDir = new File(outputDir);
        try {
            if (classesDir.exists()) {
                return classesDir.getCanonicalPath();
            }
        } catch (IOException x) {
            String classesDirAbsPath = classesDir.getAbsolutePath();
            getLog().debug("IOException obtaining canonical path name for a project's classes directory: " + classesDirAbsPath);
            return classesDirAbsPath;
        }
        return null; // directory does not exist.
    }

    /**
     * Returns the EE major version detected for the given MavenProjects
     * 
     * @param mavenProjects project modules, for single module projects list of size 1
     * @return the latest version of EE detected across multiple project modules,
     *         null if an EE version is not found or the version number is out of range
     */
    private static final String JAKARTA_PLATFORM_NAME="jakartaee-"; // jakartaee-10.0 etc.
    private static final String JAVAEE_PLATFORM_NAME="javaee-"; // javaee-7.0 etc.
    public String getEEVersion(List<MavenProject> mavenProjects, ServerFeatureUtil servUtil) {
        String eeVersion = null;
        if (mavenProjects != null) {
            Set<String> eeVersionsDetected = new HashSet<String>();
            for (MavenProject mavenProject : mavenProjects) {
                String ver = getEEVersion(mavenProject);
                getLog().debug("Java and/or Jakarta EE umbrella dependency version: " + ver + " found in project: " + mavenProject.getName());
                if (ver != null) {
                    eeVersionsDetected.add(ver);
                }
            }
            eeVersion = findMaxVersion(eeVersionsDetected);
            if (eeVersionsDetected.size() > 1) {
                getLog().info("Multiple Java EE and/or Jakarta EE versions found across multiple project modules, using the latest version (" +
                    eeVersion + ") found to generate Liberty features.");
            }
        }
        // if the dependencies do not indicate the Jakarta version then reference the platform specified in server.xml
        // E.g. pom may specify jakarta.persistence:jakarta.persistence-api:2.2.3 to compile but does not specify Jakarta 9.1
        if (eeVersion == null) {
            eeVersion = getPlatformVersion(JAKARTA_PLATFORM_NAME, servUtil);
        }
        if (eeVersion == null) {
            eeVersion = getPlatformVersion(JAVAEE_PLATFORM_NAME, servUtil);
        }
        return eeVersion;
    }

    /**
     * Returns the EE major version detected for the given MavenProject.
     * To match the Maven "nearest in the dependency tree" strategy, this method
     * will return the first EE umbrella dependency version detected.
     * 
     * @param project the MavenProject to search
     * @return EE major version corresponding to the EE umbrella dependency
     */
    private String getEEVersion(MavenProject project) {
        if (project == null) {
            return null;
        }
        List<Dependency> dependencies = project.getDependencies();
        Set<String> eeVersionsDetected = new HashSet<String>();
        for (Dependency d : dependencies) {
            String scope = d.getScope();
            String groupId = d.getGroupId();
            String artifactId = d.getArtifactId();
            if (scope == null || groupId == null || artifactId == null) {
                continue;
            }
            if (!scope.equals("provided") && !scope.equals("compile") && !scope.equals("import")) {
                continue;
            }
            if ((groupId.equals("javax") && artifactId.equals("javaee-api")) ||
                (groupId.equals("jakarta.platform") &&
                    (artifactId.equals("jakarta.jakartaee-api") ||
                    artifactId.equals("jakarta.jakartaee-web-api") ||
                    artifactId.equals("jakarta.jakartaee-core-api") ||
                    artifactId.equals("jakarta.jakartaee-bom") ||
                    artifactId.equals("jakartaee-api-parent")))) {
                eeVersionsDetected.add(d.getVersion());
            }
        }
        return findMaxVersion(eeVersionsDetected);
    }

    // Find the highest version number in the set of strings
    // returns null if the set of strings is empty
    private String findMaxVersion(Set<String> versionsDetected) {
        String maxVersion = null;
        if (!versionsDetected.isEmpty()) {
            maxVersion = versionsDetected.iterator().next();
            if (versionsDetected.size() == 1) {
                return maxVersion;
            }
            ComparableVersion cMaxVersion = new ComparableVersion(maxVersion);
            // if multiple EE/MP versions are found across multiple modules, return the latest version
            for (String ver : versionsDetected) {
                ComparableVersion cVer = new ComparableVersion(ver);
                getLog().debug("GenerateFeraturesMojo.findMaxVersion, ver=" + ver);
                if (cVer.compareTo(cMaxVersion) > 0) {
                    maxVersion = ver;
                    cMaxVersion = cVer;
                }
            }
        }
        return maxVersion;
    }

    /**
     * Returns the MicroProfile version detected for the given MavenProjects
     * 
     * @param mavenProjects project modules, for single module projects list of size 1
     * @return the latest version of MP detected across multiple project modules,
     *         null if an MP version is not found or the version number is out of range
     */
    private static final String MP_PLATFORM_NAME="microProfile-"; // microProfile-7.0 etc.
    public String getMPVersion(List<MavenProject> mavenProjects, ServerFeatureUtil servUtil) {
        String mpVersion = null;
        if (mavenProjects != null) {
            Set<String> mpVersionsDetected = new HashSet<String>();
            for (MavenProject mavenProject : mavenProjects) {
                String ver = getMPVersion(mavenProject);
                getLog().debug("MicroProfile umbrella dependency version: " + ver + " found in project: " + mavenProject.getName());
                if (ver != null) {
                    mpVersionsDetected.add(ver);
                }
            }
            // if multiple MP versions are found across multiple modules, return the latest version
            mpVersion = findMaxVersion(mpVersionsDetected);
            if (mpVersionsDetected.size() > 1) {
                getLog().info("Multiple MicroProfile versions found across multiple project modules, using the latest version (" +
                    mpVersion + ") found to generate Liberty features.");
            }
        }
        if (mpVersion == null) {
            mpVersion = getPlatformVersion(MP_PLATFORM_NAME, servUtil);
        }
        return mpVersion;
    }

    /**
     * Returns the MicroProfile (MP) version detected for the given MavenProject
     * To match the Maven "nearest in the dependency tree" strategy, this method
     * will return the first MP umbrella dependency version detected.
     * 
     * @param project the MavenProject to search
     * @return MP exact version code corresponding to the MP umbrella dependency
     */
    public String getMPVersion(MavenProject project) {
        if (project == null) {
            return null;
        }
        List<Dependency> dependencies = project.getDependencies();
        for (Dependency d : dependencies) {
            if (!d.getScope().equals("provided")) {
                continue;
            }
            if (d.getGroupId().equals("org.eclipse.microprofile") &&
                    d.getArtifactId().equals("microprofile")) {
                return d.getVersion();
            }
        }
        return null;
    }

    // Retrieve all platforms from the server.xml and related files and look for the platform specified.
    // Platforms have the format jakartaee-10.0 or microProfile-7.1. Just return the version number (10.0 or 7.1 in these examples).
    private String getPlatformVersion(String platformName, ServerFeatureUtil servUtil) {
        Set<String> platforms = getServerPlatforms(servUtil, null, false);
        for (String p : platforms) {
            getLog().debug("GenerateFeaturesMojo.getPlatformVersion, searching for platform:" + platformName + " platform=" + p);
            if (p.startsWith(platformName)) {
                return p.substring(platformName.length());
            }
        }
        return null;
    }

    // Define the logging functions of the binary scanner handler and make it available in this plugin
    private class BinaryScannerHandler extends BinaryScannerUtil {
        BinaryScannerHandler(File scannerFile) {
            super(scannerFile);
        }
        @Override
        public void debug(String msg) {
            getLog().debug(msg);
        }
        @Override
        public void debug(String msg, Throwable t) {
            getLog().debug(msg, t);
        }
        @Override
        public void error(String msg) {
            getLog().error(msg);
        }
        @Override
        public void warn(String msg) {
            getLog().warn(msg);
        }
        @Override
        public void info(String msg) {
            getLog().info(msg);
        }
        @Override
        public boolean isDebugEnabled() {
            return getLog().isDebugEnabled();
        }
    }

    // using the current MavenSession build the project (resolves dependencies)
    private MavenProject getMavenProject(File buildFile) throws ProjectBuildingException {
        ProjectBuildingResult build = mavenProjectBuilder.build(buildFile,
                session.getProjectBuildingRequest().setResolveDependencies(true));
        return build.getProject();
    }
}
