package net.wasdev.wlp.maven.test.app;

import static org.junit.Assert.*;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

import org.junit.Test;
import org.junit.Assert;

public class MergeServerEnvLtpaTest {

    @Test
    public void testServerEnvFileExists() throws Exception {
        File f1 = new File("liberty/wlp/usr/servers/test", "server.env");
        assertTrue(f1.getCanonicalFile() + " doesn't exist", f1.exists());
    }

    /**
     * Test that ltpa_keys_password is automatically generated by Liberty 26.0.0.4 and merged.
     * 
     * This is the key test - verifying that:
     * 1. Liberty 26.0.0.4 auto-generates ltpa_keys_password in default server.env
     * 2. The auto-generated ltpa_keys_password is preserved during merge
     * 3. User-provided properties are also merged correctly
     * 
     * Final expected values:
     * - keystore_password: <auto-generated by Liberty 26.0.0.4>
     * - ltpa_keys_password: <auto-generated by Liberty 26.0.0.4> - THIS IS THE KEY VERIFICATION
     * - TEST_PROP_1: fromServerEnvFile
     * - TEST_PROP_2: fromConfigDir
     * - CUSTOM_PROP: customValue
     */
    @Test
    public void testLtpaKeysPasswordAutoGenerated() throws Exception {
        File serverEnv = new File("liberty/wlp/usr/servers/test", "server.env");
        try (Scanner s = new Scanner(serverEnv)) {
            Map<String, String> serverEnvContents = new HashMap<String, String>();
            boolean commentFound = false;
            
            while (s.hasNextLine()) {
                String line = s.nextLine();
                // Ignore comment lines
                if (!line.startsWith("#") && !line.trim().isEmpty()) {
                    String[] keyValuePair = line.split("=", 2);
                    if (keyValuePair.length == 2) {
                        String key = keyValuePair[0].trim();
                        String value = keyValuePair[1].trim();
                        serverEnvContents.put(key, value);
                    }
                } else if (line.startsWith("#")) {
                    if (line.contains("liberty-maven-plugin")) {
                        commentFound = true;
                    }
                }
            }
            
            // Verify the file was generated by liberty-maven-plugin
            Assert.assertTrue("Expected 'Generated by liberty-maven-plugin' comment not found", commentFound);
            
            // Verify keystore_password from Liberty 26.0.0.4 is preserved
            Assert.assertTrue("keystore_password should be present (auto-generated by Liberty 26.0.0.4)", 
                    serverEnvContents.containsKey("keystore_password"));
            
            // KEY VERIFICATION: ltpa_keys_password should be present and auto-generated by Liberty 26.0.0.4
            Assert.assertTrue("ltpa_keys_password should be present (auto-generated by Liberty 26.0.0.4)", 
                    serverEnvContents.containsKey("ltpa_keys_password"));
            
            // Verify ltpa_keys_password has a non-empty value (auto-generated)
            Assert.assertFalse("ltpa_keys_password should have a non-empty auto-generated value", 
                    serverEnvContents.get("ltpa_keys_password").isEmpty());
            
            // Verify other merged properties
            Assert.assertTrue("TEST_PROP_1 should be present from serverEnvFile", 
                    serverEnvContents.containsKey("TEST_PROP_1"));
            Assert.assertEquals("TEST_PROP_1 should have value from serverEnvFile", 
                    "fromServerEnvFile", serverEnvContents.get("TEST_PROP_1"));
            
            Assert.assertTrue("TEST_PROP_2 should be present from configDir", 
                    serverEnvContents.containsKey("TEST_PROP_2"));
            Assert.assertEquals("TEST_PROP_2 should have value from configDir", 
                    "fromConfigDir", serverEnvContents.get("TEST_PROP_2"));
            
            Assert.assertTrue("CUSTOM_PROP should be present from pom.xml", 
                    serverEnvContents.containsKey("CUSTOM_PROP"));
            Assert.assertEquals("CUSTOM_PROP should have value from pom.xml", 
                    "customValue", serverEnvContents.get("CUSTOM_PROP"));
            
            // Verify minimum number of properties (auto-generated + user-provided)
            Assert.assertTrue("Number of env properties should be >= 5, but is " + serverEnvContents.size(), 
                    serverEnvContents.size() >= 5);
        }
    }

    /**
     * Test that both special properties (keystore_password and ltpa_keys_password) 
     * are auto-generated by Liberty 26.0.0.4 and preserved during merge.
     */
    @Test
    public void testBothSpecialPropertiesAutoGenerated() throws Exception {
        File serverEnv = new File("liberty/wlp/usr/servers/test", "server.env");
        try (Scanner s = new Scanner(serverEnv)) {
            Map<String, String> serverEnvContents = new HashMap<String, String>();
            
            while (s.hasNextLine()) {
                String line = s.nextLine();
                if (!line.startsWith("#") && !line.trim().isEmpty()) {
                    String[] keyValuePair = line.split("=", 2);
                    if (keyValuePair.length == 2) {
                        String key = keyValuePair[0].trim();
                        String value = keyValuePair[1].trim();
                        serverEnvContents.put(key, value);
                    }
                }
            }
            
            // Both special properties should be present (auto-generated by Liberty 26.0.0.4)
            Assert.assertTrue("keystore_password should be auto-generated by Liberty 26.0.0.4", 
                    serverEnvContents.containsKey("keystore_password"));
            Assert.assertTrue("ltpa_keys_password should be auto-generated by Liberty 26.0.0.4", 
                    serverEnvContents.containsKey("ltpa_keys_password"));
            
            // Verify both have non-empty values
            Assert.assertFalse("keystore_password should have a non-empty auto-generated value", 
                    serverEnvContents.get("keystore_password").isEmpty());
            Assert.assertFalse("ltpa_keys_password should have a non-empty auto-generated value", 
                    serverEnvContents.get("ltpa_keys_password").isEmpty());
        }
    }

    /**
     * Test that the merge preserves auto-generated ltpa_keys_password along with user properties.
     * This verifies the mergeSpecialPropsFromInstallServerEnvIfAbsent functionality.
     */
    @Test
    public void testAutoGeneratedLtpaPasswordPreservedDuringMerge() throws Exception {
        File serverEnv = new File("liberty/wlp/usr/servers/test", "server.env");
        try (Scanner s = new Scanner(serverEnv)) {
            Map<String, String> serverEnvContents = new HashMap<String, String>();
            
            while (s.hasNextLine()) {
                String line = s.nextLine();
                if (!line.startsWith("#") && !line.trim().isEmpty()) {
                    String[] keyValuePair = line.split("=", 2);
                    if (keyValuePair.length == 2) {
                        String key = keyValuePair[0].trim();
                        String value = keyValuePair[1].trim();
                        serverEnvContents.put(key, value);
                    }
                }
            }
            
            // Verify ltpa_keys_password is present (auto-generated and preserved)
            Assert.assertTrue("ltpa_keys_password should be preserved from Liberty 26.0.0.4 auto-generation", 
                    serverEnvContents.containsKey("ltpa_keys_password"));
            
            // Verify user properties are also present (proving merge worked)
            Assert.assertTrue("TEST_PROP_1 should be merged from serverEnvFile", 
                    serverEnvContents.containsKey("TEST_PROP_1"));
            Assert.assertTrue("TEST_PROP_2 should be merged from configDir", 
                    serverEnvContents.containsKey("TEST_PROP_2"));
            Assert.assertTrue("CUSTOM_PROP should be merged from pom.xml", 
                    serverEnvContents.containsKey("CUSTOM_PROP"));
            
            // This proves that auto-generated ltpa_keys_password was preserved during merge
            Assert.assertEquals("TEST_PROP_1 value should be correct", 
                    "fromServerEnvFile", serverEnvContents.get("TEST_PROP_1"));
            Assert.assertEquals("TEST_PROP_2 value should be correct", 
                    "fromConfigDir", serverEnvContents.get("TEST_PROP_2"));
            Assert.assertEquals("CUSTOM_PROP value should be correct", 
                    "customValue", serverEnvContents.get("CUSTOM_PROP"));
        }
    }
}