package net.wasdev.wlp.maven.test.app;

import static org.junit.Assert.*;

import java.io.File;
import java.util.HashMap;
import java.util.Map;
import java.util.Scanner;

import org.junit.Test;
import org.junit.Assert;

/**
 * Integration test for mergeServerEnv functionality with ltpa_keys_password.
 * 
 * This test verifies that the ltpa_keys_password field is properly merged
 * from the install server.env when mergeServerEnv is enabled.
 * 
 * Test scenario:
 * - Default server.env (from Liberty install) contains: keystore_password and ltpa_keys_password
 * - serverEnvFile contains: ltpa_keys_password=myLtpaPassword123, TEST_PROP_1=fromServerEnvFile
 * - configDir/server.env contains: TEST_PROP_2=fromConfigDir, ltpa_keys_password=configDirLtpaPassword
 * - pom.xml properties contain: CUSTOM_PROP=customValue
 * 
 * Expected merge order (later sources override earlier ones):
 * 1. Default server.env from Liberty install (keystore_password, ltpa_keys_password)
 * 2. configDir/server.env (TEST_PROP_2, ltpa_keys_password - overrides default)
 * 3. serverEnvFile (TEST_PROP_1, ltpa_keys_password - overrides configDir)
 * 4. pom.xml properties (CUSTOM_PROP - highest priority)
 * 
 * The test verifies that:
 * - Both keystore_password and ltpa_keys_password from default server.env are preserved
 * - ltpa_keys_password is properly merged with correct precedence
 * - All other properties are merged correctly
 * - The file is marked as generated by liberty-maven-plugin
 */
public class MergeServerEnvLtpaTest {

    @Test
    public void testServerEnvFileExists() throws Exception {
        File f1 = new File("liberty/wlp/usr/servers/test", "server.env");
        assertTrue(f1.getCanonicalFile() + " doesn't exist", f1.exists());
    }

    /**
     * Test the complete merge scenario with ltpa_keys_password.
     * 
     * Merge order and expected values:
     * 1. Default server.env: keystore_password=<default>, ltpa_keys_password=<default>
     * 2. configDir/server.env: TEST_PROP_2=fromConfigDir, ltpa_keys_password=configDirLtpaPassword (overrides default)
     * 3. serverEnvFile: TEST_PROP_1=fromServerEnvFile, ltpa_keys_password=myLtpaPassword123 (overrides configDir)
     * 4. pom.xml: CUSTOM_PROP=customValue (highest priority)
     * 
     * Final expected values:
     * - keystore_password: <from default server.env>
     * - ltpa_keys_password: myLtpaPassword123 (from serverEnvFile, highest priority for this property)
     * - TEST_PROP_1: fromServerEnvFile
     * - TEST_PROP_2: fromConfigDir
     * - CUSTOM_PROP: customValue
     */
    @Test
    public void testLtpaKeysPasswordMerging() throws Exception {
        File serverEnv = new File("liberty/wlp/usr/servers/test", "server.env");
        try (Scanner s = new Scanner(serverEnv)) {
            Map<String, String> serverEnvContents = new HashMap<String, String>();
            boolean commentFound = false;
            
            while (s.hasNextLine()) {
                String line = s.nextLine();
                // Ignore comment lines
                if (!line.startsWith("#") && !line.trim().isEmpty()) {
                    String[] keyValuePair = line.split("=", 2);
                    if (keyValuePair.length == 2) {
                        String key = keyValuePair[0].trim();
                        String value = keyValuePair[1].trim();
                        serverEnvContents.put(key, value);
                    }
                } else if (line.startsWith("#")) {
                    if (line.contains("liberty-maven-plugin")) {
                        commentFound = true;
                    }
                }
            }
            
            // Verify the file was generated by liberty-maven-plugin
            Assert.assertTrue("Expected 'Generated by liberty-maven-plugin' comment not found", commentFound);
            
            // Verify keystore_password from default server.env is preserved
            Assert.assertTrue("keystore_password should be present from default server.env", 
                    serverEnvContents.containsKey("keystore_password"));
            
            // Verify ltpa_keys_password is present and has the correct value from serverEnvFile
            Assert.assertTrue("ltpa_keys_password should be present", 
                    serverEnvContents.containsKey("ltpa_keys_password"));
            Assert.assertEquals("ltpa_keys_password should have value from serverEnvFile (highest priority)", 
                    "myLtpaPassword123", serverEnvContents.get("ltpa_keys_password"));
            
            // Verify other merged properties
            Assert.assertTrue("TEST_PROP_1 should be present from serverEnvFile", 
                    serverEnvContents.containsKey("TEST_PROP_1"));
            Assert.assertEquals("TEST_PROP_1 should have value from serverEnvFile", 
                    "fromServerEnvFile", serverEnvContents.get("TEST_PROP_1"));
            
            Assert.assertTrue("TEST_PROP_2 should be present from configDir", 
                    serverEnvContents.containsKey("TEST_PROP_2"));
            Assert.assertEquals("TEST_PROP_2 should have value from configDir", 
                    "fromConfigDir", serverEnvContents.get("TEST_PROP_2"));
            
            Assert.assertTrue("CUSTOM_PROP should be present from pom.xml", 
                    serverEnvContents.containsKey("CUSTOM_PROP"));
            Assert.assertEquals("CUSTOM_PROP should have value from pom.xml", 
                    "customValue", serverEnvContents.get("CUSTOM_PROP"));
            
            // Verify minimum number of properties (should have at least the ones we explicitly set plus defaults)
            Assert.assertTrue("Number of env properties should be >= 5, but is " + serverEnvContents.size(), 
                    serverEnvContents.size() >= 5);
        }
    }

    /**
     * Test that both special properties (keystore_password and ltpa_keys_password) 
     * are preserved from the default server.env when mergeServerEnv is enabled.
     */
    @Test
    public void testBothSpecialPropertiesPreserved() throws Exception {
        File serverEnv = new File("liberty/wlp/usr/servers/test", "server.env");
        try (Scanner s = new Scanner(serverEnv)) {
            Map<String, String> serverEnvContents = new HashMap<String, String>();
            
            while (s.hasNextLine()) {
                String line = s.nextLine();
                if (!line.startsWith("#") && !line.trim().isEmpty()) {
                    String[] keyValuePair = line.split("=", 2);
                    if (keyValuePair.length == 2) {
                        String key = keyValuePair[0].trim();
                        String value = keyValuePair[1].trim();
                        serverEnvContents.put(key, value);
                    }
                }
            }
            
            // Both special properties should be present
            Assert.assertTrue("keystore_password should be preserved from default server.env", 
                    serverEnvContents.containsKey("keystore_password"));
            Assert.assertTrue("ltpa_keys_password should be preserved/merged", 
                    serverEnvContents.containsKey("ltpa_keys_password"));
            
            // Verify keystore_password has a non-empty value
            Assert.assertFalse("keystore_password should have a non-empty value", 
                    serverEnvContents.get("keystore_password").isEmpty());
            
            // Verify ltpa_keys_password has the expected merged value
            Assert.assertEquals("ltpa_keys_password should have the merged value", 
                    "myLtpaPassword123", serverEnvContents.get("ltpa_keys_password"));
        }
    }

    /**
     * Test that ltpa_keys_password from serverEnvFile takes precedence over configDir.
     */
    @Test
    public void testLtpaPasswordPrecedence() throws Exception {
        File serverEnv = new File("liberty/wlp/usr/servers/test", "server.env");
        try (Scanner s = new Scanner(serverEnv)) {
            Map<String, String> serverEnvContents = new HashMap<String, String>();
            
            while (s.hasNextLine()) {
                String line = s.nextLine();
                if (!line.startsWith("#") && !line.trim().isEmpty()) {
                    String[] keyValuePair = line.split("=", 2);
                    if (keyValuePair.length == 2) {
                        String key = keyValuePair[0].trim();
                        String value = keyValuePair[1].trim();
                        serverEnvContents.put(key, value);
                    }
                }
            }
            
            // ltpa_keys_password should have value from serverEnvFile, not from configDir
            Assert.assertEquals("ltpa_keys_password should be from serverEnvFile (not configDirLtpaPassword)", 
                    "myLtpaPassword123", serverEnvContents.get("ltpa_keys_password"));
            Assert.assertNotEquals("ltpa_keys_password should not be from configDir", 
                    "configDirLtpaPassword", serverEnvContents.get("ltpa_keys_password"));
        }
    }
}
