/**
 * Inventory App
 * App for storing JVM system properties of various hosts.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.openliberty.guides.inventory.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

import io.openliberty.guides.inventory.model.SystemData;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.json.bind.annotation.JsonbProperty;

/**
  * POJO that represents the inventory contents.
 **/
public class InventoryList  {
  
  private List<SystemData> systems = new ArrayList<SystemData>();

  private Integer total;
  
 /**
   * Get systems
   * @return systems
  **/
  @JsonbProperty("systems")
  public List<SystemData> getSystems() {
    return systems;
  }

  /**
    * Set systems
  **/
  public void setSystems(List<SystemData> systems) {
    this.systems = systems;
  }

  public InventoryList systems(List<SystemData> systems) {
    this.systems = systems;
    return this;
  }

  public InventoryList addSystemsItem(SystemData systemsItem) {
    this.systems.add(systemsItem);
    return this;
  }

 /**
   * Get total
   * @return total
  **/
  @JsonbProperty("total")
  public Integer getTotal() {
    return total;
  }

  /**
    * Set total
  **/
  public void setTotal(Integer total) {
    this.total = total;
  }

  public InventoryList total(Integer total) {
    this.total = total;
    return this;
  }


  /**
    * Create a string representation of this pojo.
  **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InventoryList {\n");
    
    sb.append("    systems: ").append(toIndentedString(systems)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

