/**
 * Inventory App
 * App for storing JVM system properties of various hosts.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.openliberty.guides.inventory.model;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.json.bind.annotation.JsonbProperty;

/**
  * POJO that represents a single inventory entry.
 **/
public class SystemData  {
  
  private String hostname;

  private Map<String, String> properties = new HashMap<String, String>();
  
 /**
   * Get hostname
   * @return hostname
  **/
  @JsonbProperty("hostname")
  public String getHostname() {
    return hostname;
  }

  /**
    * Set hostname
  **/
  public void setHostname(String hostname) {
    this.hostname = hostname;
  }

  public SystemData hostname(String hostname) {
    this.hostname = hostname;
    return this;
  }

 /**
   * Get properties
   * @return properties
  **/
  @JsonbProperty("properties")
  public Map<String, String> getProperties() {
    return properties;
  }

  /**
    * Set properties
  **/
  public void setProperties(Map<String, String> properties) {
    this.properties = properties;
  }

  public SystemData properties(Map<String, String> properties) {
    this.properties = properties;
    return this;
  }

  public SystemData putPropertiesItem(String key, String propertiesItem) {
    this.properties.put(key, propertiesItem);
    return this;
  }


  /**
    * Create a string representation of this pojo.
  **/
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SystemData {\n");
    
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    properties: ").append(toIndentedString(properties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

