package net.wasdev.wlp.maven.test.app;

import static org.junit.Assert.*;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;

import org.junit.Test;
import org.junit.Assert;


/**
 * 
 * MergeServerEnv - tests mergeServerEnv=true with convertServerEnvPathSeparator=true.
 * Values with backslashes are converted to forward-slashes (legacy behaviour).
 * 
 */
public class MergeServerEnvTest {

    @Test
    public void testServerEnvFileExists() throws Exception {
        File f1 = new File("liberty/wlp/usr/servers/test", "server.env");
        assertTrue(f1.getCanonicalFile() + " doesn't exist", f1.exists());
    }

    /*
        # envProps in pom.xml
        <properties>
            <liberty.env.TEST_PROP_2>white</liberty.env.TEST_PROP_2>
            <liberty.env.CONFIG_SERVER_ENV_PROPS>TEST</liberty.env.CONFIG_SERVER_ENV_PROPS>
        </properties>
        
        # default server.env
        keystore_password=sfKRrA1ioLdtIFQC9bEfkua
        ltpa_keys_password=<default_value>

        # Configured server.env
        CONFIG_SERVER_ENV=TEST
        TEST_PROP_2=green
        TEST_PROP_3=blue

        # server.env in configDir
        ConfigDir=TEST
        TEST_PROP_1=red
        TEST_PROP_2=red
        TEST_PROP_3=red

        # Merged server.env (with convertServerEnvPathSeparator=true: backslashes converted)
        # Generated by liberty-maven-plugin
        keystore_password=sfKRrA1ioLdtIFQC9bEfkua
        ltpa_keys_password=<default_value>
        CONFIG_SERVER_ENV=TEST
        ConfigDir=TEST
        TEST_PROP_3=blue
        CONFIG_SERVER_ENV_PROPS=TEST
        TEST_PROP_2=white
        TEST_PROP_1=red
        WIN_HOME=C:/myfolder/folder2
        WIN_JAVA_HOME=!WIN_HOME!/java
        TEST_BACKSLASH_VALUE=abc/`;xyz
    */
    @Test
    public void check_server_env_contents() throws Exception {
        File serverEnv = new File("liberty/wlp/usr/servers/test", "server.env");
        try (Scanner s = new Scanner(serverEnv)) {
            Map<String,String> serverEnvContents = new HashMap<String,String>();
            boolean commentFound = false;
            while(s.hasNextLine()) {
                String line = s.nextLine();
                if(!line.startsWith("#")) {
                    String[] keyValuePair = line.split("=", 2);
                    String key = keyValuePair[0];
                    String value = keyValuePair[1];
                    serverEnvContents.put(key,value);
                } else {
                    commentFound = true;
                    Assert.assertTrue("File should have been generated by liberty-maven-plugin", line.contains("liberty-maven-plugin"));
                }
            }
            Assert.assertTrue("Expected generated by liberty-maven-plugin comment not found", commentFound);

            Assert.assertTrue("Number of env properties should be >= 12, but is "+serverEnvContents.size(), serverEnvContents.size() >= 12);
            Assert.assertTrue("keystore_password mapping found", serverEnvContents.containsKey("keystore_password"));
            Assert.assertTrue("ltpa_keys_password mapping found", serverEnvContents.containsKey("ltpa_keys_password"));
            Assert.assertTrue("ConfigDir=TEST mapping found", serverEnvContents.get("ConfigDir").equals("TEST"));
            Assert.assertTrue("CONFIG_SERVER_ENV=TEST mapping found", serverEnvContents.get("CONFIG_SERVER_ENV").equals("TEST"));
            Assert.assertTrue("TEST_PROP_3=blue", serverEnvContents.get("TEST_PROP_3").equals("blue"));
            Assert.assertTrue("CONFIG_SERVER_ENV_PROPS=TEST", serverEnvContents.get("CONFIG_SERVER_ENV_PROPS").equals("TEST"));
            Assert.assertTrue("TEST_PROP_2=white", serverEnvContents.get("TEST_PROP_2").equals("white"));
            Assert.assertTrue("TEST_PROP_1=red", serverEnvContents.get("TEST_PROP_1").equals("red"));
            // convertServerEnvPathSeparator=true: backslashes must be converted to forward-slashes.
            Assert.assertTrue("WIN_HOME: backslash converted to forward-slash", serverEnvContents.get("WIN_HOME").equals("C:/myfolder/folder2"));
            Assert.assertTrue("WIN_JAVA_HOME: backslash converted to forward-slash", serverEnvContents.get("WIN_JAVA_HOME").equals("!WIN_HOME!/java"));
            Assert.assertTrue("TEST_BACKSLASH_VALUE: backslash converted to forward-slash", serverEnvContents.get("TEST_BACKSLASH_VALUE").equals("abc/`;xyz"));
        }
    }

}
