# Start with OL runtime.
# tag::from[]
FROM icr.io/appcafe/open-liberty:full-java11-openj9-ubi
# end::from[]

ARG VERSION=1.0
ARG REVISION=SNAPSHOT
# tag::label[]

LABEL \
  org.opencontainers.image.authors="Your Name" \
  org.opencontainers.image.vendor="IBM" \
  org.opencontainers.image.url="local" \
  org.opencontainers.image.source="https://github.com/OpenLiberty/guide-docker" \
  org.opencontainers.image.version="$VERSION" \
  org.opencontainers.image.revision="$REVISION" \
  vendor="Open Liberty" \
  name="system" \
  version="$VERSION-$REVISION" \
  summary="The system microservice from the Docker Guide" \
  # tag::description[]
  description="This image contains the system microservice running with the Open Liberty runtime."
  # end::description[]
# end::label[]


USER root

COPY --chown=1001:0 src/main/liberty/config/server.xml /config/

COPY --chown=1001:0 target/*.war /config/apps/

USER 1001
