package net.wasdev.wlp.maven.test.app;

import static org.junit.Assert.*;

import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;

import org.junit.Test;
import org.junit.Assert;


/**
 * MergeServerEnvVerbatimTest - verifies that mergeServerEnv=true with the DEFAULT
 * convertServerEnvPathSeparator=false writes all server.env values verbatim.
 * Backslashes in Windows paths and delayed-expansion variable references must
 * be preserved unchanged in the merged output.
 */
public class MergeServerEnvVerbatimTest {

    @Test
    public void testServerEnvFileExists() throws Exception {
        File f1 = new File("liberty/wlp/usr/servers/test", "server.env");
        assertTrue(f1.getCanonicalFile() + " doesn't exist", f1.exists());
    }

    @Test
    public void check_server_env_contents() throws Exception {
        File serverEnv = new File("liberty/wlp/usr/servers/test", "server.env");
        try (Scanner s = new Scanner(serverEnv)) {
            Map<String,String> serverEnvContents = new HashMap<String,String>();
            boolean commentFound = false;
            while(s.hasNextLine()) {
                String line = s.nextLine();
                if(!line.startsWith("#")) {
                    String[] keyValuePair = line.split("=", 2);
                    String key = keyValuePair[0];
                    String value = keyValuePair[1];
                    serverEnvContents.put(key, value);
                } else {
                    commentFound = true;
                    Assert.assertTrue("File should have been generated by liberty-maven-plugin", line.contains("liberty-maven-plugin"));
                }
            }
            Assert.assertTrue("Expected generated by liberty-maven-plugin comment not found", commentFound);

            Assert.assertTrue("Number of env properties should be >= 13, but is "+serverEnvContents.size(), serverEnvContents.size() >= 13);
            Assert.assertTrue("keystore_password mapping found", serverEnvContents.containsKey("keystore_password"));
            Assert.assertTrue("ltpa_keys_password mapping found", serverEnvContents.containsKey("ltpa_keys_password"));
            Assert.assertTrue("ConfigDir=TEST", serverEnvContents.get("ConfigDir").equals("TEST"));
            Assert.assertTrue("CONFIG_SERVER_ENV=TEST", serverEnvContents.get("CONFIG_SERVER_ENV").equals("TEST"));
            Assert.assertTrue("TEST_PROP_3=blue", serverEnvContents.get("TEST_PROP_3").equals("blue"));
            Assert.assertTrue("CONFIG_SERVER_ENV_PROPS=TEST", serverEnvContents.get("CONFIG_SERVER_ENV_PROPS").equals("TEST"));
            Assert.assertTrue("TEST_PROP_2=white", serverEnvContents.get("TEST_PROP_2").equals("white"));
            Assert.assertTrue("TEST_PROP_1=red", serverEnvContents.get("TEST_PROP_1").equals("red"));
            // Gradle inline property with backslash path: verbatim (convertServerEnvPathSeparator=false default).
            Assert.assertTrue("MAVEN_WIN_PATH=C:\\Semeru\\jdk verbatim", serverEnvContents.get("MAVEN_WIN_PATH").equals("C:\\Semeru\\jdk"));
        }
    }

    /**
     * Regression test: mergeServerEnv=true with convertServerEnvPathSeparator=false (default)
     * must not corrupt Windows paths, delayed-expansion variable references, or any value
     * containing a backslash written verbatim in a user's server.env file.
     *
     * Entries in src/test/resources/server.env:
     *   WIN_HOME=C:\myfolder\folder2        (Windows backslash path)
     *   WIN_JAVA_HOME=!WIN_HOME!\java       (delayed-expansion variable reference)
     *   UNIX_HOME=/usr/local/myapp          (Unix forward-slash path — unchanged on all platforms)
     *   TEST_BACKSLASH_VALUE=abc\`;xyz      (arbitrary mid-string backslash)
     */
    @Test
    public void check_windows_path_and_expansion_variables_preserved() throws Exception {
        File serverEnv = new File("liberty/wlp/usr/servers/test", "server.env");
        assertTrue(serverEnv.getCanonicalFile() + " doesn't exist", serverEnv.exists());

        Map<String, String> serverEnvContents = new HashMap<String, String>();
        try (Scanner s = new Scanner(serverEnv)) {
            while (s.hasNextLine()) {
                String line = s.nextLine();
                if (!line.startsWith("#") && !line.trim().isEmpty()) {
                    String[] kv = line.split("=", 2);
                    if (kv.length == 2) {
                        serverEnvContents.put(kv[0], kv[1]);
                    }
                }
            }
        }

        String os = System.getProperty("os.name");
        boolean isWindows = os != null && os.toLowerCase().startsWith("windows");

        Assert.assertTrue("WIN_HOME key present", serverEnvContents.containsKey("WIN_HOME"));
        Assert.assertTrue("WIN_JAVA_HOME key present", serverEnvContents.containsKey("WIN_JAVA_HOME"));
        Assert.assertTrue("UNIX_HOME key present", serverEnvContents.containsKey("UNIX_HOME"));
        Assert.assertTrue("TEST_BACKSLASH_VALUE key present", serverEnvContents.containsKey("TEST_BACKSLASH_VALUE"));

        if (isWindows) {
            Assert.assertEquals("WIN_HOME backslash preserved", "C:\\myfolder\\folder2", serverEnvContents.get("WIN_HOME"));
            Assert.assertEquals("WIN_JAVA_HOME backslash preserved", "!WIN_HOME!\\java", serverEnvContents.get("WIN_JAVA_HOME"));
        } else {
            Assert.assertFalse("WIN_HOME not converted to forward-slash: " + serverEnvContents.get("WIN_HOME"),
                    serverEnvContents.get("WIN_HOME").contains("/myfolder/folder2"));
            Assert.assertFalse("WIN_JAVA_HOME not converted to forward-slash",
                    serverEnvContents.get("WIN_JAVA_HOME").contains("!WIN_HOME!/java"));
        }

        Assert.assertEquals("UNIX_HOME unchanged", "/usr/local/myapp", serverEnvContents.get("UNIX_HOME"));
        Assert.assertEquals("TEST_BACKSLASH_VALUE verbatim", "abc\\`;xyz", serverEnvContents.get("TEST_BACKSLASH_VALUE"));
    }

    /**
     * Order test: WIN_HOME must appear before WIN_JAVA_HOME in the merged server.env
     * so Liberty can resolve the !WIN_HOME! expansion reference at server start.
     */
    @Test
    public void check_expansion_variable_order_preserved() throws Exception {
        File serverEnv = new File("liberty/wlp/usr/servers/test", "server.env");
        assertTrue(serverEnv.getCanonicalFile() + " doesn't exist", serverEnv.exists());

        List<String> keys = new ArrayList<String>();
        try (Scanner s = new Scanner(serverEnv)) {
            while (s.hasNextLine()) {
                String line = s.nextLine();
                if (!line.startsWith("#") && !line.trim().isEmpty()) {
                    String[] kv = line.split("=", 2);
                    if (kv.length == 2) {
                        keys.add(kv[0]);
                    }
                }
            }
        }

        int winHomeIndex = keys.indexOf("WIN_HOME");
        int winJavaHomeIndex = keys.indexOf("WIN_JAVA_HOME");

        Assert.assertTrue("WIN_HOME present", winHomeIndex >= 0);
        Assert.assertTrue("WIN_JAVA_HOME present", winJavaHomeIndex >= 0);
        Assert.assertTrue(
                "WIN_HOME (pos " + winHomeIndex + ") must appear before WIN_JAVA_HOME (pos " + winJavaHomeIndex + ")",
                winHomeIndex < winJavaHomeIndex);
    }

}
